apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimer
  namespace: uptimer-app
spec:
  selector:
    matchLabels:
      app: uptimer
  template:
    metadata:
      labels:
        app: uptimer
    spec:
      containers:
      - name: uptimer
        image: savchenkodn79/uptimer:7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uptimer
  namespace: uptimer-app
spec:
  selector:
    app: uptimer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort

